### ISSUE TITLE
Query Params are removed when we have a link-to 

### ISSUE THREAD

**Issue by MiguelMadero** [MiguelMadero/ember-cli-bundle-loader#11]
When deep-linking or `{{link-to}}`ing to a lazy loaded route the queryParams are gone. 

![query-params-bug](https://cloud.githubusercontent.com/assets/47388/17974881/aa8d1c44-6a9c-11e6-8ed1-278a81574097.gif)

Notes: 
* This may affect transitionTo, redirect and replace as well. 
* This may be related to https://github.com/MiguelMadero/ember-cli-bundle-loader/pull/4 and https://github.com/MiguelMadero/ember-cli-bundle-loader/pull/8. The error happens with and without the changes from those PRs. 
* When navigating manually (changing the URL), the queryParams are preseved

**Comment by MiguelMadero** [comment]
@hyderali can you check if PR#8 fixed your issue? Not sure if this is the same that you originally reported or a slight variation. As you can see from the GIF above, the URL is correct.

**Comment by MiguelMadero** [comment]
Fixed by https://github.com/MiguelMadero/ember-cli-bundle-loader/pull/12

**Comment by hyderali** [comment]
@MiguelMadero , this is a different issue than the one I reported earlier. I was about to open this issue and you have fixed it already. 👍

**Comment by MiguelMadero** [comment]
That's great to know. 

I've been working on this project a lot more actively now at work, so ping me if you find any issues I appreciate your feedback, but please also have a good look at the progress we have done with engines lazy-loading. While this project won't go away anytime soon, engines is a better long-term investment and it's almost on par with what this project can do.

**Comment by hyderali** [comment]
@MiguelMadero , thanks for the updates.
We have two more requirements:
 1. `Fingerprinting`- We don't fingerprint the assets in production build, as we maintain versions by a different approach. And you have done this in #13 . 👍 
 2. A loading indicator while the assets are loaded. I've tried transitioning to loading route when the assets are loaded. But that adds an entry in the history, and replaceWith too doesn't suits here. Is there any other way we can show a loading indicator when the assets are loaded.
This will sum up our requirements.

**Comment by hyderali** [comment]
With all your help, we have successfully moved a module as a package to production. And we are working in moving other modules too.
Meanwhile, we are experimenting with engines too. We'll provide our feedbacks once we are ready with it.  

Any plans for supporting this addon for ember versions > 2.1.
With this [commit](https://github.com/emberjs/ember.js/commit/c1256491085eaa23f9005830074e05f66fe794c2) Container#_registry is changed to Container#registry and hence the addon breaks.

**Comment by MiguelMadero** [comment]
1. :D 
2. Can you use a loading substate in the current route? It's working for now, we have one at the application level and it just uses that. 

> With all your help, we have successfully moved a module as a package to production

That's so awesome!!! Congrats :D 

> Any plans for supporting this addon for ember versions > 2.1.

I'm all up for it. Do you think you can send a PR? Sounds like you're really close, maybe it's a matter of changing our reference to something like `container._registry || container.registry` so it works in 1.13 and above. Nice find!
