### ISSUE TITLE
integration test failure for components in consumer app

### ISSUE THREAD

**Issue by gokatz** [MiguelMadero/ember-cli-bundle-loader#3]
integration test fails when I add a component (test-comp) into the [consumer app](https://github.com/MiguelMadero/ember-cli-bundle-loader-consumer). The error is due the `htmlbars-inline-precompile` package. 

The full error message is as follow

`Died on test #1     at Object.TestLoader.moduleLoadFailure (http://localhost:4200/assets/test-support.js:6364:11)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:69:14)
    at Object.loadModules (http://localhost:4200/assets/test-loader.js:58:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:89:24)
    at http://localhost:4200/assets/test-support.js:6373:16: Could not find module `htmlbars-inline-precompile` imported from `ember-cli-bundle-loader-consumer/tests/integration/components/test-comp-test`@ 1 ms

Source: 	
Error: Could not find module `htmlbars-inline-precompile` imported from `ember-cli-bundle-loader-consumer/tests/integration/components/test-comp-test`
    at missingModule (http://localhost:4200/assets/vendor.js:173:11)
    at findModule (http://localhost:4200/assets/vendor.js:188:17)
    at Module.reify (http://localhost:4200/assets/vendor.js:124:22)
    at Module.build (http://localhost:4200/assets/vendor.js:142:23)
    at findModule (http://localhost:4200/assets/vendor.js:190:9)
    at requireModule (http://localhost:4200/assets/vendor.js:177:12)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:67:9)
    at Object.loadModules (http://localhost:4200/assets/test-loader.js:58:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:89:24)
    at http://localhost:4200/assets/test-support.js:6373:16`

 ---

I tried changing the `ember-cli-htmlbars-inline-precompile` package fro devDeps to Deps. Still the error persist.

**Comment by MiguelMadero** [comment]
Hi @gokulk13 I'm sorry I missed your message. I'll have a look, I thought this was working fine, but now that you mention it this might be the same cause to an issue we have in our app :D

**Comment by gokulk13** [comment]
Thanks for the time @MiguelMadero, But I tried this add-on with a different app, the same error kills my integration test. I'm digging the CLI for bundling and build process...

**Comment by MiguelMadero** [comment]
Im working on the addon next week and will look into this.

**Comment by gokatz** [comment]
Hi @MiguelMadero,
Update over this issue: when I change the order of the arguments passed for the EmberApp [here](https://github.com/MiguelMadero/ember-cli-bundle-loader/blob/master/lib/broccoli/ember-app-with-packages.js#L74) as in this [fork](https://github.com/gokatz/ember-cli-bundle-loader/blob/master/lib/broccoli/ember-app-with-packages.js#L74) , my integration test gets passed. I think, `defaults` must be passed as the first argument for `merge-defaults` so that other arguments will get include in `defaults` itself. Later, we will be making use of the `defaults` for creating [package](https://github.com/MiguelMadero/ember-cli-bundle-loader/blob/master/lib/broccoli/ember-app-with-packages.js#L129)

**Comment by MiguelMadero** [comment]
Makes sense. Can you send a PR?
Im on vacations, but have some time to review, merge and release either
tomorrow or over the weekend.

**Comment by gokatz** [comment]
Sure.. Will update the space with a PR by tomorrow morning.

**Comment by gokatz** [comment]
PR #7 will be having the changes.

**Comment by MiguelMadero** [comment]
This was fixed and released as 0.2.3. I published it to npm now to make it easier to consume. 

[Diff between 0.2.2 and 0.2.3](https://github.com/MiguelMadero/ember-cli-bundle-loader/compare/v0.2.2...v0.2.3)
